export enum NotificationType {
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  PROJECT_SHARED = 'PROJECT_SHARED',
  PROJECT_ARCHIVED = 'PROJECT_ARCHIVED',
  FILE_UPLOADED = 'FILE_UPLOADED',
  FILE_DELETED = 'FILE_DELETED',
  FILE_SHARED = 'FILE_SHARED',
  TEAM_INVITATION = 'TEAM_INVITATION',
  TEAM_MEMBER_ADDED = 'TEAM_MEMBER_ADDED',
  TEAM_MEMBER_REMOVED = 'TEAM_MEMBER_REMOVED',
  MEMBER_JOINED_TEAM = 'MEMBER_JOINED_TEAM',
  MEMBER_LEFT_TEAM = 'MEMBER_LEFT_TEAM',
  COMMENT_ADDED = 'COMMENT_ADDED',
  MENTION = 'MENTION',
  SYSTEM = 'SYSTEM',
}

export enum NotificationStatus {
  UNREAD = 'UNREAD',
  READ = 'READ',
  ARCHIVED = 'ARCHIVED',
  DELETED = 'DELETED',
}
